### ISSUE TITLE
Sonar needs a license

### ISSUE THREAD

**Issue by jlyman** [mandatoryprogrammer/sonar#8]
It'd be great to know what we can do with Sonar to make sure we're in the clear. I'm always a fan of MIT or BSD new for its flexibility, and it seems like larger (corporate) parties are often more likely to contribute with those as well.

**Comment by mandatoryprogrammer** [comment]
While I'm not super familiar with the differences between all of the different open source licenses (took a bit of Googling) it appears MIT is a good fit for this project. I've added it as it seems to be the most "do what you want" license.

**Comment by moloch--** [comment]
https://tldrlegal.com/
