### ISSUE TITLE
Feature Request: Inspect realm in HTTP headers for additional clues

### ISSUE THREAD

**Issue by jlyman** [mandatoryprogrammer/sonar#9]
Many devices will be rather explicit with their make/model in the WWW-Authenticate realm header. Just one more (often easy and straightforward) clue to grab the right info.

Example: `WWW-Authenticate: Basic realm="TP-LINK Wireless Dual Band Gigabit Router Archer C7"`

Didn't know how to do it in JS, but here's a good StackOverflow post about how to accomplish it: http://stackoverflow.com/a/4881836/549346

**Comment by mandatoryprogrammer** [comment]
I don't think this will be possible due to this being a violation of the same origin policy. An XMLHTTPRequest will throw a CORS error due to this. Unless realms are an exception to SOP (such as window.name, the image dimensions, etc.)

**Comment by jlyman** [comment]
Ah indeed, that'd be true. I'm using Sonar right now inside of PhantomJS with security turned off, and had forgotten about that little restriction. Too bad you can't read the headers directly off of referenced resources... Good call.
